num1 = float(input("First Number: "))
num2 = float(input("Second Number: "))
print("Addition:", num1 + num2)
print("Subtraction:", num1 - num2)
print("Multiplication:", num1 * num2)
print("Division:", num1 / num2)
num1 = float(input("First Number: "))
num2 = float(input("Second Number: "))
print("addition:",num1+num2)
print("multiplication:",num1*num2)
print("division:" , num2/num1)
